/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as PlayersHandleRouteImport } from './routes/players.$handle'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersHandleRoute = PlayersHandleRouteImport.update({
  id: '/players/$handle',
  path: '/players/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamsRoute,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/players/$handle': typeof PlayersHandleRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/players/$handle': typeof PlayersHandleRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/players/$handle': typeof PlayersHandleRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$handle'
    | '/teams/$slug'
    | '/tournaments/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$handle'
    | '/teams/$slug'
    | '/tournaments/$slug'
  id:
    | '__root__'
    | '/'
    | '/rankings'
    | '/teams'
    | '/tournaments'
    | '/players/$handle'
    | '/teams/$slug'
    | '/tournaments/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingsRoute: typeof RankingsRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
  PlayersHandleRoute: typeof PlayersHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$handle': {
      id: '/players/$handle'
      path: '/players/$handle'
      fullPath: '/players/$handle'
      preLoaderRoute: typeof PlayersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsSlugRoute: typeof TeamsSlugRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsSlugRoute: TeamsSlugRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingsRoute: RankingsRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
  PlayersHandleRoute: PlayersHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
