// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin / trusted competitive operations only.
// For normal signed-in user queries, use the auth middleware client so RLS stays active.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function looksLikeServerSecret(value: string | undefined): boolean {
  const key = value?.trim();
  if (!key) return false;
  if (key.startsWith("sb_secret_")) return true;
  // Legacy Supabase service_role keys are JWTs.
  return key.split(".").length === 3 && key.startsWith("eyJ");
}

/**
 * Whether trusted DB writes can run in this server process.
 * Lovable Cloud provides this server-side; it is intentionally not part of
 * the browser/public .env contract.
 */
export function isSupabaseAdminConfigured(): boolean {
  return (
    Boolean(process.env["SUPABASE_URL"]?.trim()) &&
    looksLikeServerSecret(process.env["SUPABASE_SERVICE_ROLE_KEY"])
  );
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"]?.trim();
  const SUPABASE_SERVICE_ROLE_KEY = process.env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();

  if (!SUPABASE_URL) {
    const message = "Missing Supabase environment variable: SUPABASE_URL.";
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!looksLikeServerSecret(SUPABASE_SERVICE_ROLE_KEY)) {
    const message =
      "Trusted Supabase server credential is unavailable. This operation must run in Lovable Cloud or another trusted backend configured with SUPABASE_SERVICE_ROLE_KEY.";
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY!),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers or other .server.ts modules only.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
